In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [95]:
data = pd.read_csv("data_60_points.csv")
final_df = pd.read_csv("real_trainable_data.csv")

In [97]:
final_df

0          1          2          3          4          5  \
0      24.292663  19.482136   8.624346  -0.932498  -0.395269  -0.455120   
1      13.989555  10.538844   4.357757  -4.671976  -2.448575  -0.195571   
2      28.226338  22.926922  12.568386   5.334923   5.037145   4.942274   
3      10.275999   4.947967  -2.816720  -0.592784   3.641866   4.649932   
4      25.701159  19.995006   9.928850   2.699057   3.008508   3.815365   
...          ...        ...        ...        ...        ...        ...   
24475  11.155567   4.922098  -3.461332  -4.032277  -1.114526  -1.513674   
24476   6.996882   2.759212  -3.510316 -12.739806 -11.527527 -10.179139   
24477  10.081258   3.523532  -7.159546 -11.535609  -6.292619  -2.571509   
24478   6.268450  -0.157610  -6.713017  -7.677638  -7.921744 -10.210587   
24479  10.505622   4.058037  -4.002375  -4.866927  -4.306062  -4.782621   

              6         7         8         9        10         11         12  \
0      0.855522  0.265530  0.903650  0.375534  6.494048  10.806570  16.298106   
1      0.800786  3.143261  5.239468  4.201113  8.261465  14.473524  19.864308   
2      5.231862  5.857457  4.706730  3.209744  7.516828  11.593123  12.189684   
3      2.646541 -1.270290 -2.929141 -6.799285  3.601604  10.222119  19.432944   
4      4.283556  5.071418  6.786370  5.908505  7.489823   8.131428  20.692792   
...         ...       ...       ...       ...       ...        ...        ...   
24475 -1.338061 -2.400368 -2.691510 -3.048169  7.857754  15.840349  21.116623   
24476 -5.917935 -4.149302 -3.697041 -4.776158  3.006573  10.141209  14.015408   
24477 -2.313104 -1.138576  0.494965 -1.253445 -2.600577   0.768775   6.544863   
24478 -7.826407 -2.057707 -0.051476 -1.256450 -1.921820  12.964946  22.052552   
24479 -5.644187 -5.433851 -4.300399 -3.462145 -0.394352   8.246392  12.588591   

              13         14         15         16         17         18  \
0      22.642826  30.166633  32.797640  35.965448  36.856227  38.217799   
1      24.504377  26.899719  29.828029  30.846174  34.612770  36.322818   
2      24.144492  34.429614  39.251816  42.360987  42.153320  40.232554   
3      24.399276  26.055434  30.721370  34.252714  36.724282  40.113567   
4      28.606421  31.868476  31.369655  34.818414  35.152058  38.765068   
...          ...        ...        ...        ...        ...        ...   
24475  25.446394  29.771683  30.832026  34.940365  36.416927  36.002649   
24476  17.139618  24.838357  29.376673  33.248166  35.317520  34.729822   
24477  12.629293  22.614272  28.104815  30.158691  31.427458  33.260984   
24478  27.137271  29.548358  29.622495  28.714233  26.733114  27.801140   
24479  23.073970  28.783233  30.678644  29.888858  36.924449  40.613638   

              19         20         21         22         23         24  \
0      40.515852  44.777485  47.852875  47.984674  44.949001  39.392795   
1      39.871013  40.660836  40.509061  43.573435  44.646330  46.281056   
2      39.260015  41.433838  40.561513  40.530602  42.918988  42.958990   
3      39.735524  41.583358  40.384044  39.774486  39.177502  35.668568   
4      38.795564  40.917534  40.544992  43.677075  42.821196  40.771396   
...          ...        ...        ...        ...        ...        ...   
24475  36.464240  38.625030  38.765290  41.249646  42.635470  44.641132   
24476  35.715585  37.556933  37.289891  36.441240  35.875983  34.738707   
24477  33.104519  34.907133  37.960187  39.404214  40.663027  39.071995   
24478  27.329231  27.396700  31.587603  33.786771  36.523247  36.186644   
24479  42.352442  41.555844  38.128840  38.971161  42.439057  43.831163   

              25         26         27         28         29         30  \
0      41.983571  41.751005  39.821448  39.306901  35.898327  31.267594   
1      45.589177  42.310204  36.523023  34.340195  28.664981  22.112208   
2      44.177509  44.904055  43.775191  42.127408  41.367294  38.782862   
3      35.275721  38.441500  40.383033 

## ----- testing ----

In [5]:
#This onwards is testing since CNN (convolutional neural networks) require certain dimensions and the data above is not
#how it is required. I have not yet got that part correctly. Maybe another try can be with some other technique, like SVM
#other any other with the data above, or the required trasformations.

In [55]:
testing = np.array(data)
channels = 8
data_points = 60
rows = int(testing.shape[0]/channels)

testing = testing.reshape(rows,channels,data_points)
testing.shape

(24480, 8, 60)

In [56]:
#testing = np.transpose(testing,(0,2,1)) #swapping the dimensions of the first and second dimension
#testing = np.moveaxis(testing,1,2)
testing[0,0,:]

array([ 24.29266315,  19.48213606,   8.62434618,  -0.93249795,
        -0.395269  ,  -0.45511959,   0.85552233,   0.26553007,
         0.90364979,   0.37553439,   6.49404827,  10.80657046,
        16.29810641,  22.64282591,  30.16663306,  32.79763987,
        35.96544763,  36.85622728,  38.21779915,  40.51585161,
        44.77748515,  47.85287506,  47.98467419,  44.94900146,
        39.39279476,  41.98357109,  41.75100534,  39.82144845,
        39.30690095,  35.89832734,  31.26759443,  28.99148835,
        29.49316214,  27.26890834,  24.621208  ,  19.16474037,
         9.36460695,  -2.79193057,  -2.9038967 ,  -6.95035885,
        -5.4698337 ,  -5.30440495,  -6.7844437 , -11.02684303,
       -14.94093665, -18.74570367, -16.04137975, -13.575005  ,
       -11.91399572, -11.40620428, -13.58474193, -17.7753692 ,
       -23.82847803, -29.68844043, -27.82596152, -28.73588454,
       -25.56327793, -23.95641506, -24.07171348, -25.72319523])

In [11]:
testing.shape

(24480, 60, 8)

In [12]:
testing[0,0,:]

array([24.29266315, 13.98955519, 28.22633846, 10.27599949, 25.7011592 ,
        8.78540736, 25.63732919,  9.94014041])

# Train Test Split

In [13]:
inputs = testing

In [14]:
inputs

array([[[ 24.29266315,  13.98955519,  28.22633846, ...,   8.78540736,
          25.63732919,   9.94014041],
        [ 19.48213606,  10.53884378,  22.92692172, ...,   3.43229632,
          20.01987867,   3.50816165],
        [  8.62434618,   4.35775745,  12.56838637, ...,  -3.57635655,
           9.04231123,  -9.03445603],
        ...,
        [-23.95641506, -32.90878499, -18.74202104, ..., -37.07345309,
         -19.19802768, -29.79290376],
        [-24.07171348, -29.10308578, -18.91035331, ..., -31.40481203,
         -17.44934579, -28.08923238],
        [-25.72319523, -26.50364474, -16.05159439, ..., -28.95965915,
         -16.75149523, -28.63564027]],

       [[ 19.89690772,  13.59079517,  21.76846978, ...,  15.62146155,
          25.35015354,  19.03803218],
        [ 13.44733366,   5.29455776,  16.08370541, ...,  11.26126993,
          19.06618013,  14.74662409],
        [  1.75833183,  -8.4935791 ,   4.77559825, ...,   5.48320985,
           7.83089717,   3.67842121],
        ...,


In [15]:
targets = final_df.iloc[:,final_df.columns.size-1]
targets = np.array(targets.astype(int))
targets

array([ 1,  2,  3, ..., 10, 11, 12])

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(inputs, targets, test_size = 0.1, random_state = 42)

In [17]:
#from sklearn.preprocessing import StandardScaler

#maybe later

#scaler = StandardScaler()
#x_train = scaler.fit_transform(x_train)
#x_test = scaler.transform(x_test)

In [ ]:
#Try: LSTM in here or from the following link in matlab: 

# https://www.mathworks.com/help/deeplearning/ug/classify-sequence-data-using-lstm-networks.html