In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("data_60_points.csv")
final_df = pd.read_csv("trainable_data.csv")

In [3]:
data = np.array(data)  #all trials, in all channels, in all subjects, just displayed in the 60 data points
print(data.shape)
data

(195840, 60)


array([[ 24.29266315,  19.48213606,   8.62434618, ..., -23.95641506,
        -24.07171348, -25.72319523],
       [ 13.98955519,  10.53884378,   4.35775745, ..., -32.90878499,
        -29.10308578, -26.50364474],
       [ 28.22633846,  22.92692172,  12.56838637, ..., -18.74202104,
        -18.91035331, -16.05159439],
       ...,
       [ 14.74133757,   9.63969112,   0.26182729, ..., -28.16465467,
        -24.80088919, -20.91094823],
       [ 21.63027251,  17.21599496,  12.80081119, ..., -27.91419764,
        -23.27303582, -21.76826698],
       [ 11.7598485 ,   3.79086613,  -4.07664358, ..., -25.03038999,
        -21.4713802 , -20.17446601]])

In [4]:
final_df

POz  \
0      [ 24.29266315  19.48213606   8.62434618  -0.93...   
1      [ 13.98955519  10.53884378   4.35775745  -4.67...   
2      [ 2.82263385e+01  2.29269217e+01  1.25683864e+...   
3      [ 10.27599949   4.94796666  -2.81671978  -0.59...   
4      [ 25.7011592   19.99500644   9.92884956   2.69...   
...                                                  ...   
24475  [ 17.40127817  11.48818209   0.62965744  -1.58...   
24476  [ 11.39666306   3.14104721  -8.39463475  -8.06...   
24477  [ 10.48047578   3.83750389  -2.83178831  -5.41...   
24478  [  7.59868963   0.92075536  -7.35398578  -3.06...   
24479  [ 20.44164597  16.62982096   6.14503985  -5.57...   

                                                     PO3  \
0      [ 20.30557886  16.53533043   6.01671273  -2.90...   
1      [ 27.73215155  24.31906164  14.86712932   2.48...   
2      [ 18.83898212  14.34074265   3.51585031  -6.33...   
3      [ 26.60238147  23.80177241  16.21661482   2.04...   
4      [ 11.11728466   3.60259753 -10.11846013  -6.43...   
...                                                  ...   
24475  [ 11.95316151   4.86812128  -2.46677062  -6.00...   
24476  [ 14.49768595   5.82461908  -4.03770858  -4.45...   
24477  [  9.56665318   4.63450725  -2.39242101  -6.43...   
24478  [ 10.11898055   4.92419067  -3.8395779   -2.70...   
24479  [ 12.3687479    3.85435497  -8.88225564  -8.04...   

                                                     PO4  \
0      [ 11.7979369    5.18400824  -5.71926855  -2.67...   
1      [ 11.92485715   8.54491075   3.41320573  -2.36...   
2      [ 1.32124402e+01  6.42557407e+00 -5.42326658e+...   
3      [ 10.49070886   4.60042316  -4.30221152  -2.65...   
4      [ 14.72852458   6.88362502  -6.28421523  -4.25...   
...                                                  ...   
24475  [ 9.98051846e+00  4.36174447e+00 -2.00636992e+...   
24476  [ 12.54673162   7.32983901  -1.29166408  -7.78...   
24477  [ 15.9152505   10.76756377   0.25017327  -7.68...   
24478  [ 1.60239843e+01  1.16873682e+01  8.71220215e-...   
24479  [ 10.05650671   3.70924014  -6.72330478  -7.62...   

                                                     PO5  \
0      [  8.51350644   0.1708112   -8.60835025  -8.10...   
1      [ 10.62157458   2.35556977  -7.52206943  -4.51...   
2      [ 27.72075501  24.06891511  15.54283486   1.22...   
3      [ 26.1687615   23.02603533  13.72217123  -3.08...   
4      [ 12.45149595   6.18561092  -0.37667144  -1.82...   
...                                                  ...   
24475  [  9.46482095   2.97192404  -6.48243696  -8.86...   
24476  [ 16.47530441   8.74956628   0.26882383   1.39...   
24477  [  8.54608359   2.03619106  -7.19693794  -8.42...   
24478  [ 21.8989065   15.62827815   5.06994819  -1.41...   
24479  [ 10.60353957   3.51873014  -4.38043092  -6.06...   

                                                     PO6  \
0      [ 29.36678077  26.30161727  17.39629899  10.88...   
1      [ 20.99168618  18.78192841  13.11527782  14.72...   
2      [ 19.56471878  17.17939013  11.8750772    3.23...   
3      [ 24.80989474  21.0337573   16.78709027  18.45...   
4      [ 14.18883022  10.7496074    5.38028944   3.23...   
...                                                  ...   
24475  [ 13.7423822    9.62111216   1.20842324   1.63...   
24476  [ 20.66978035  16.25446351   9.95760726  13.22...   
24477  [ 17.03429546  13.12048998   7.00022132   8.35...   
24478  [ 24.9500061   19.23910252  12.683399    12.19...   
24479  [ 16.45490938  13.13459702   8.4100695    8.87...   

                                                      Oz  \
0      [ 18.49610762  14.17785633   8.09876914   8.32...   
1      [ 19.88508128  18.11352735  13.75600985  12.47...   
2      [ 19.26586349  15.98193076  10.17602519  10.58...   
3      [ 17.34979045  14.89982078   9.89211726  14.66...   
4      [ 21.93677334  17.69292276  12.30548628  19.58...   
...                                                  ...   
24475  [  5.80906509  -0.360

## ----- testing ----

In [5]:
#This onwards is testing since CNN (convolutional neural networks) require certain dimensions and the data above is not
#how it is required. I have not yet got that part correctly. Maybe another try can be with some other technique, like SVM
#other any other with the data above, or the required trasformations.

In [6]:
#concatenating lists in a single cell to create columns:

POz = pd.DataFrame(final_df.POz.tolist())
PO3 = pd.DataFrame(final_df.PO3.tolist())
PO4 = pd.DataFrame(final_df.PO4.tolist())
PO5 = pd.DataFrame(final_df.PO5.tolist())
PO6 = pd.DataFrame(final_df.PO6.tolist())
Oz = pd.DataFrame(final_df.Oz.tolist())
O1 = pd.DataFrame(final_df.O1.tolist())
O2 = pd.DataFrame(final_df.O2.tolist())

concatenated = pd.concat([POz,PO3,PO4,PO5,PO6,Oz,O1,O2],axis=1)
concatenated.columns = range(concatenated.columns.size)
concatenated.shape

(24480, 8)

In [7]:
concatenated

0  \
0      [ 24.29266315  19.48213606   8.62434618  -0.93...   
1      [ 13.98955519  10.53884378   4.35775745  -4.67...   
2      [ 2.82263385e+01  2.29269217e+01  1.25683864e+...   
3      [ 10.27599949   4.94796666  -2.81671978  -0.59...   
4      [ 25.7011592   19.99500644   9.92884956   2.69...   
...                                                  ...   
24475  [ 17.40127817  11.48818209   0.62965744  -1.58...   
24476  [ 11.39666306   3.14104721  -8.39463475  -8.06...   
24477  [ 10.48047578   3.83750389  -2.83178831  -5.41...   
24478  [  7.59868963   0.92075536  -7.35398578  -3.06...   
24479  [ 20.44164597  16.62982096   6.14503985  -5.57...   

                                                       1  \
0      [ 20.30557886  16.53533043   6.01671273  -2.90...   
1      [ 27.73215155  24.31906164  14.86712932   2.48...   
2      [ 18.83898212  14.34074265   3.51585031  -6.33...   
3      [ 26.60238147  23.80177241  16.21661482   2.04...   
4      [ 11.11728466   3.60259753 -10.11846013  -6.43...   
...                                                  ...   
24475  [ 11.95316151   4.86812128  -2.46677062  -6.00...   
24476  [ 14.49768595   5.82461908  -4.03770858  -4.45...   
24477  [  9.56665318   4.63450725  -2.39242101  -6.43...   
24478  [ 10.11898055   4.92419067  -3.8395779   -2.70...   
24479  [ 12.3687479    3.85435497  -8.88225564  -8.04...   

                                                       2  \
0      [ 11.7979369    5.18400824  -5.71926855  -2.67...   
1      [ 11.92485715   8.54491075   3.41320573  -2.36...   
2      [ 1.32124402e+01  6.42557407e+00 -5.42326658e+...   
3      [ 10.49070886   4.60042316  -4.30221152  -2.65...   
4      [ 14.72852458   6.88362502  -6.28421523  -4.25...   
...                                                  ...   
24475  [ 9.98051846e+00  4.36174447e+00 -2.00636992e+...   
24476  [ 12.54673162   7.32983901  -1.29166408  -7.78...   
24477  [ 15.9152505   10.76756377   0.25017327  -7.68...   
24478  [ 1.60239843e+01  1.16873682e+01  8.71220215e-...   
24479  [ 10.05650671   3.70924014  -6.72330478  -7.62...   

                                                       3  \
0      [  8.51350644   0.1708112   -8.60835025  -8.10...   
1      [ 10.62157458   2.35556977  -7.52206943  -4.51...   
2      [ 27.72075501  24.06891511  15.54283486   1.22...   
3      [ 26.1687615   23.02603533  13.72217123  -3.08...   
4      [ 12.45149595   6.18561092  -0.37667144  -1.82...   
...                                                  ...   
24475  [  9.46482095   2.97192404  -6.48243696  -8.86...   
24476  [ 16.47530441   8.74956628   0.26882383   1.39...   
24477  [  8.54608359   2.03619106  -7.19693794  -8.42...   
24478  [ 21.8989065   15.62827815   5.06994819  -1.41...   
24479  [ 10.60353957   3.51873014  -4.38043092  -6.06...   

                                                       4  \
0      [ 29.36678077  26.30161727  17.39629899  10.88...   
1      [ 20.99168618  18.78192841  13.11527782  14.72...   
2      [ 19.56471878  17.17939013  11.8750772    3.23...   
3      [ 24.80989474  21.0337573   16.78709027  18.45...   
4      [ 14.18883022  10.7496074    5.38028944   3.23...   
...                                                  ...   
24475  [ 13.7423822    9.62111216   1.20842324   1.63...   
24476  [ 20.66978035  16.25446351   9.95760726  13.22...   
24477  [ 17.03429546  13.12048998   7.00022132   8.35...   
24478  [ 24.9500061   19.23910252  12.683399    12.19...   
24479  [ 16.45490938  13.13459702   8.4100695    8.87...   

                                                       5  \
0      [ 18.49610762  14.17785633   8.09876914   8.32...   
1      [ 19.88508128  18.11352735  13.75600985  12.47...   
2      [ 19.26586349  15.98193076  10.17602519  10.58...   
3      [ 17.34979045  14.89982078   9.89211726  14.66...   
4      [ 21.93677334  17.69292276  12.30548628  19.58...   
...                                                  ...   
24475  [  5.80906509  -0.36023

In [8]:
testing = np.array(data)
channels = 8 # or int(concatenated.shape[1]/60)
data_points = 60
rows = int(testing.shape[0]/channels)

testing = testing.reshape(rows,channels,data_points)
testing.shape

(24480, 8, 60)

In [9]:
#testing = np.transpose(testing,(0,2,1)) #swapping the dimensions of the first and second dimension
testing = np.moveaxis(testing,1,2)
testing

array([[[ 24.29266315,  13.98955519,  28.22633846, ...,   8.78540736,
          25.63732919,   9.94014041],
        [ 19.48213606,  10.53884378,  22.92692172, ...,   3.43229632,
          20.01987867,   3.50816165],
        [  8.62434618,   4.35775745,  12.56838637, ...,  -3.57635655,
           9.04231123,  -9.03445603],
        ...,
        [-23.95641506, -32.90878499, -18.74202104, ..., -37.07345309,
         -19.19802768, -29.79290376],
        [-24.07171348, -29.10308578, -18.91035331, ..., -31.40481203,
         -17.44934579, -28.08923238],
        [-25.72319523, -26.50364474, -16.05159439, ..., -28.95965915,
         -16.75149523, -28.63564027]],

       [[ 19.89690772,  13.59079517,  21.76846978, ...,  15.62146155,
          25.35015354,  19.03803218],
        [ 13.44733366,   5.29455776,  16.08370541, ...,  11.26126993,
          19.06618013,  14.74662409],
        [  1.75833183,  -8.4935791 ,   4.77559825, ...,   5.48320985,
           7.83089717,   3.67842121],
        ...,


In [10]:
concatenated.iloc[0,0:60]

0    [ 24.29266315  19.48213606   8.62434618  -0.93...
1    [ 20.30557886  16.53533043   6.01671273  -2.90...
2    [ 11.7979369    5.18400824  -5.71926855  -2.67...
3    [  8.51350644   0.1708112   -8.60835025  -8.10...
4    [ 29.36678077  26.30161727  17.39629899  10.88...
5    [ 18.49610762  14.17785633   8.09876914   8.32...
6    [ 21.47188797  17.84480697   7.73288801  -5.76...
7    [ 2.53335228e+01  2.19357912e+01  1.41939680e+...
Name: 0, dtype: object

In [11]:
testing.shape

(24480, 60, 8)

In [12]:
testing[0,0,:]

array([24.29266315, 13.98955519, 28.22633846, 10.27599949, 25.7011592 ,
        8.78540736, 25.63732919,  9.94014041])

# Train Test Split

In [13]:
#inputs = concatenated

inputs = testing

In [14]:
inputs

array([[[ 24.29266315,  13.98955519,  28.22633846, ...,   8.78540736,
          25.63732919,   9.94014041],
        [ 19.48213606,  10.53884378,  22.92692172, ...,   3.43229632,
          20.01987867,   3.50816165],
        [  8.62434618,   4.35775745,  12.56838637, ...,  -3.57635655,
           9.04231123,  -9.03445603],
        ...,
        [-23.95641506, -32.90878499, -18.74202104, ..., -37.07345309,
         -19.19802768, -29.79290376],
        [-24.07171348, -29.10308578, -18.91035331, ..., -31.40481203,
         -17.44934579, -28.08923238],
        [-25.72319523, -26.50364474, -16.05159439, ..., -28.95965915,
         -16.75149523, -28.63564027]],

       [[ 19.89690772,  13.59079517,  21.76846978, ...,  15.62146155,
          25.35015354,  19.03803218],
        [ 13.44733366,   5.29455776,  16.08370541, ...,  11.26126993,
          19.06618013,  14.74662409],
        [  1.75833183,  -8.4935791 ,   4.77559825, ...,   5.48320985,
           7.83089717,   3.67842121],
        ...,


In [15]:
targets = final_df.iloc[:,final_df.columns.size-1]
targets = np.array(targets.astype(int))
targets

array([ 1,  2,  3, ..., 10, 11, 12])

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(inputs, targets, test_size = 0.1, random_state = 42)

In [17]:
#from sklearn.preprocessing import StandardScaler

#maybe later

#scaler = StandardScaler()
#x_train = scaler.fit_transform(x_train)
#x_test = scaler.transform(x_test)

In [18]:
x_train

array([[[ 24.25459911,  15.98039665,  20.19888745, ...,  16.19812859,
          24.58734903,  17.11959384],
        [ 20.60543965,  11.07686179,  16.61088245, ...,   8.80845604,
          21.78163768,  12.06686691],
        [ 11.01668853,   0.21581292,   8.36083773, ...,  -3.67774903,
          14.1704279 ,   3.3393036 ],
        ...,
        [-26.25391496, -29.2909173 , -23.20554697, ..., -27.40737945,
         -22.54584921, -30.17202088],
        [-25.14685187, -26.83294833, -21.14166613, ..., -26.70857943,
         -20.79166269, -28.16815101],
        [-24.96947041, -22.47448793, -21.82191219, ..., -25.56761716,
         -19.26769783, -26.24176861]],

       [[ 26.70044036,  12.65617929,  32.62491115, ...,   9.62969775,
          16.37528682,  12.5593562 ],
        [ 24.21677918,   5.49594902,  29.55482829, ...,   2.87442316,
          11.32034721,   3.97204757],
        [ 17.33351457,  -3.83736398,  20.78998908, ...,  -7.82668281,
           1.57768478,  -8.38360151],
        ...,


In [19]:
y_train

array([9, 2, 5, ..., 9, 4, 3])

In [21]:
x_train.shape

(22032, 60, 8)

In [22]:
K = len(set(y_train))
print("Unique classes: ", K)

Unique classes:  12


In [23]:
import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Conv2D, Conv1D, Dense, Flatten, Dropout, MaxPooling1D, GlobalMaxPooling1D
from tensorflow.keras.layers import BatchNormalization, Activation, Dropout, LSTM, Bidirectional, LeakyReLU, AveragePooling1D

## CNN

In [24]:
model = Sequential()

model.add(Conv1D(filters = 5, kernel_size = 3,strides=1,input_shape=(x_train.shape[1],x_train.shape[2]))) #1
model.add(BatchNormalization())
model.add(LeakyReLU())
model.add(MaxPooling1D(pool_size=2,strides=2)) #2
model.add(Conv1D(filters = 5, kernel_size = 3,strides=1))#3
model.add(LeakyReLU())
model.add(MaxPooling1D(pool_size=2,strides=2)) #4
model.add(Dropout(0.5))
model.add(Conv1D(filters = 5, kernel_size = 3,strides=1))#5
model.add(LeakyReLU())
model.add(AveragePooling1D(pool_size=2, strides=2))#6
model.add(Dropout(0.5))
model.add(Conv1D(filters = 5, kernel_size = 3,strides=1))#7
model.add(LeakyReLU())
model.add(AveragePooling1D(pool_size=2, strides=2))#8
#model.add(Conv1D(filters = 5, kernel_size = 3,strides=1))#9    #NANI
model.add(LeakyReLU())
model.add(GlobalMaxPooling1D())#10
model.add(Dense(K,activation='softmax'))#11

model.compile('adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [25]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience= 2)
history = model.fit(x_train,y_train,epochs = 10, batch_size=64, validation_data = (x_test, y_test), verbose = 1, callbacks = [callback])
model.summary()

Epoch 1/10
345/345 [==============================] - 8s 12ms/step - loss: nan - accuracy: 3.6311e-04 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 2/10
345/345 [==============================] - 4s 11ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 58, 5)             125       
                                                                 
 batch_normalization (BatchN  (None, 58, 5)            20        
 ormalization)                                                   
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 58, 5)             0         
                                                                 
 max_pooling1d (MaxPooling1D  (None, 29, 5)            0         
 )                            

## NN: Model Creation

In [28]:
model = Sequential()
model.add(tf.keras.layers.Input(shape= (x_train.shape[1],x_train.shape[2])))

model.add(Dense(64, activation = 'relu'))
model.add(BatchNormalization())
model.add(Activation('tanh'))
model.add(Dropout(0.2))

model.add(Dense(128, activation = 'relu'))
model.add(BatchNormalization())
model.add(Activation('tanh'))
model.add(Dropout(0.2))

model.add(Dense(256, activation = 'relu'))
model.add(BatchNormalization())
model.add(Activation('tanh'))
model.add(Dropout(0.2))

model.add(Dense(512, activation = 'relu'))
model.add(BatchNormalization())
model.add(Activation('tanh'))
model.add(Dropout(0.2))

model.add(Dense(512, activation = 'relu'))
model.add(BatchNormalization())
model.add(Activation('tanh'))
model.add(Dropout(0.2))

model.add(Dense(2, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 60, 64)            576       
                                                                 
 batch_normalization_6 (Batc  (None, 60, 64)           256       
 hNormalization)                                                 
                                                                 
 activation_5 (Activation)   (None, 60, 64)            0         
                                                                 
 dropout_7 (Dropout)         (None, 60, 64)            0         
                                                                 
 dense_8 (Dense)             (None, 60, 128)           8320      
                                                                 
 batch_normalization_7 (Batc  (None, 60, 128)          512       
 hNormalization)                                      

In [29]:
custom_optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer = custom_optimizer, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience= 2)
history = model.fit(x_train,y_train,epochs = 3, batch_size=64, validation_data = (x_test,y_test), verbose = 1, callbacks = [callback])
model.summary()

#So bad... 0.000something accuracy.. garbage in garbage out

Epoch 1/3


InvalidArgumentError: Graph execution error:

Detected at node 'Equal' defined at (most recent call last):
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
      self._run_once()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
      handle._run()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 504, in dispatch_queue
      await self.process_one()
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 493, in process_one
      await dispatch(*args)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 400, in dispatch_shell
      await result
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 724, in execute_request
      reply_content = await reply_content
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
      res = shell.run_cell(
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in run_cell
      result = self._run_cell(
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 2935, in _run_cell
      return runner(coro)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3134, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3337, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\alexc\AppData\Local\Temp\ipykernel_15868\1802143674.py", line 4, in <cell line: 4>
      history = model.fit(x_train,y_train,epochs = 3, batch_size=64, validation_data = (x_test,y_test), verbose = 1, callbacks = [callback])
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 864, in train_step
      return self.compute_metrics(x, y, y_pred, sample_weight)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 957, in compute_metrics
      self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\compile_utils.py", line 459, in update_state
      metric_obj.update_state(y_t, y_p, sample_weight=mask)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\metrics_utils.py", line 70, in decorated
      update_op = update_state_fn(*args, **kwargs)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\metrics.py", line 178, in update_state_fn
      return ag_update_state(*args, **kwargs)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\metrics.py", line 729, in update_state
      matches = ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\metrics.py", line 4086, in sparse_categorical_accuracy
      return tf.cast(tf.equal(y_true, y_pred), backend.floatx())
Node: 'Equal'
required broadcastable shapes
	 [[{{node Equal}}]] [Op:__inference_train_function_8184]

## SVM try

In [ ]:
#Import svm model
from sklearn import svm

rbf = svm.SVC(kernel='rbf', gamma=0.1, C=0.1)

rbf.fit(x_train, y_train)

y_pred = rbf.predict(x_test)

# 5 min and 46.5 seconds


In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# 0.07475490196078431 accuracy KUKU
# or 7.475%

Accuracy: 0.07475490196078431
